# Copyright (c) 2026 Mostafa Elkabir. Licensed under the BSD 2-Clause License.
"""The local ticket store under ``backlog/``.

Every piece of work starts as a ticket file and ends with that file updated.
This module is the one place that knows the file format, so the index, the
CLI and the test suite agree on what a valid ticket is. It reads and writes
Markdown files; it never touches the database.

The rules it enforces are the ones that keep a file-based backlog honest when
several agents share it:

* a ticket that is being worked on names who holds it and on which branch,
  so a second agent does not pick it up too;
* a ticket cannot be ``done`` without the pull request that closed it and a
  written outcome, so the record of what shipped is never an empty heading;
* a ticket cannot be ``ready`` while something it depends on is still open,
  so "pick the top ready ticket" is a safe instruction.
"""

from __future__ import annotations

import re
from dataclasses import dataclass, field
from datetime import UTC, date, datetime
from pathlib import Path
from typing import TYPE_CHECKING, Any

import yaml

if TYPE_CHECKING:
    from collections.abc import Callable

ID_PATTERN = re.compile(r"^T-\d{3}$")
HTML_COMMENT = re.compile(r"<!--.*?-->", re.DOTALL)
FILENAME_PATTERN = re.compile(r"^(T-\d{3})-[a-z0-9]+(?:-[a-z0-9]+)*\.md$")

STATUSES: tuple[str, ...] = ("backlog", "ready", "in-progress", "in-review", "done", "dropped")
OPEN_STATUSES: frozenset[str] = frozenset({"backlog", "ready", "in-progress", "in-review"})
CLOSED_STATUSES: frozenset[str] = frozenset({"done", "dropped"})
PRIORITIES: tuple[str, ...] = ("P0", "P1", "P2", "P3")
# The roadmap's phases. A ticket names one so the index groups honestly.
PHASES: tuple[str, ...] = (
    "0-process",
    "1-drive",
    "2-gate",
    "3-accuracy",
    "4-second-connector",
    "5-on-prem",
)

REQUIRED_SECTIONS: tuple[str, ...] = (
    "Problem",
    "Definition",
    "Success metrics",
    "Test cases",
    "Work log",
    "Outcome",
)

INDEX_HEADER = """# Backlog

Generated by `go2 backlog index` from the files in `tickets/`. Do not edit
by hand: edit the ticket, then regenerate. `go2 backlog check` fails when
this file is stale, and the fast tests run that check.

How to work from this file: [README.md](README.md).
"""


class TicketError(ValueError):
    """A ticket file that does not satisfy the format."""


@dataclass
class Ticket:
    """One ticket, parsed from its Markdown file."""

    path: Path
    id: str
    title: str
    status: str
    phase: str
    priority: str
    created: date
    updated: date
    blocked_by: list[str] = field(default_factory=list)
    github_issue: int | None = None
    owner: str | None = None
    branch: str | None = None
    pr: str | None = None
    closed: date | None = None
    sections: dict[str, str] = field(default_factory=dict)

    @property
    def is_open(self) -> bool:
        """True while the ticket still needs work or review."""
        return self.status in OPEN_STATUSES

    @property
    def link(self) -> str:
        """Path relative to the ``backlog/`` directory, for the index."""
        return f"tickets/{self.path.name}"


def default_root() -> Path:
    """The ``backlog/`` directory of this checkout."""
    return Path(__file__).resolve().parent.parent / "backlog"


# --- Parsing ----------------------------------------------------------------


def _split_frontmatter(text: str, path: Path) -> tuple[dict[str, Any], str]:
    if not text.startswith("---\n"):
        msg = f"{path.name}: must start with a '---' frontmatter block"
        raise TicketError(msg)
    end = text.find("\n---\n", 4)
    if end == -1:
        msg = f"{path.name}: frontmatter block is not closed"
        raise TicketError(msg)
    try:
        meta = yaml.safe_load(text[4:end])
    except yaml.YAMLError as exc:
        msg = f"{path.name}: frontmatter is not valid YAML: {exc}"
        raise TicketError(msg) from exc
    if not isinstance(meta, dict):
        msg = f"{path.name}: frontmatter must be a mapping"
        raise TicketError(msg)
    return meta, text[end + 5 :]


def _sections(body: str) -> dict[str, str]:
    """Section text by heading. Comments are stripped so a template placeholder is empty."""
    body = HTML_COMMENT.sub("", body)
    found: dict[str, str] = {}
    current: str | None = None
    lines: list[str] = []
    for line in body.splitlines():
        if line.startswith("## "):
            if current is not None:
                found[current] = "\n".join(lines).strip()
            current = line[3:].strip()
            lines = []
        else:
            lines.append(line)
    if current is not None:
        found[current] = "\n".join(lines).strip()
    return found


def _as_date(value: object, name: str, path: Path) -> date:
    if isinstance(value, date):
        return value
    msg = f"{path.name}: '{name}' must be a date (YYYY-MM-DD), got {value!r}"
    raise TicketError(msg)


def _optional_str(meta: dict[str, Any], name: str, path: Path) -> str | None:
    value = meta.get(name)
    if value is None or value == "":
        return None
    if not isinstance(value, str):
        msg = f"{path.name}: '{name}' must be a string"
        raise TicketError(msg)
    return value


def _validated_meta(meta: dict[str, Any], path: Path) -> dict[str, Any]:
    """Check the frontmatter has every required key with a value of the right shape."""
    for key in ("id", "title", "status", "phase", "priority", "created", "updated"):
        if key not in meta:
            msg = f"{path.name}: frontmatter is missing '{key}'"
            raise TicketError(msg)
    ticket_id = str(meta["id"])
    checks: list[tuple[bool, str]] = [
        (bool(ID_PATTERN.match(ticket_id)), f"id {ticket_id!r} must look like T-012"),
        (path.name.startswith(ticket_id + "-"), f"filename must start with its id {ticket_id}"),
        (
            meta["status"] in STATUSES,
            f"status {meta['status']!r} is not one of {', '.join(STATUSES)}",
        ),
        (
            meta["priority"] in PRIORITIES,
            f"priority {meta['priority']!r} is not one of {', '.join(PRIORITIES)}",
        ),
        (
            meta["phase"] in PHASES,
            f"phase {meta['phase']!r} is not one of {', '.join(PHASES)}",
        ),
        (
            isinstance(meta.get("blocked_by") or [], list)
            and all(isinstance(b, str) for b in (meta.get("blocked_by") or [])),
            "'blocked_by' must be a list of ticket ids",
        ),
        (
            meta.get("github_issue") is None or isinstance(meta.get("github_issue"), int),
            "'github_issue' must be an integer",
        ),
    ]
    for ok, problem in checks:
        if not ok:
            msg = f"{path.name}: {problem}"
            raise TicketError(msg)
    return meta


def parse_ticket(path: Path) -> Ticket:
    """Parse one ticket file, checking only its own contents."""
    if not FILENAME_PATTERN.match(path.name):
        msg = f"{path.name}: filename must look like T-012-short-kebab-title.md"
        raise TicketError(msg)
    raw, body = _split_frontmatter(path.read_text(encoding="utf-8"), path)
    meta = _validated_meta(raw, path)

    sections = _sections(body)
    missing = [s for s in REQUIRED_SECTIONS if s not in sections]
    if missing:
        msg = f"{path.name}: missing section(s): {', '.join(f'## {m}' for m in missing)}"
        raise TicketError(msg)

    closed_raw = meta.get("closed")
    ticket = Ticket(
        path=path,
        id=str(meta["id"]),
        title=str(meta["title"]).strip(),
        status=meta["status"],
        phase=str(meta["phase"]),
        priority=meta["priority"],
        created=_as_date(meta["created"], "created", path),
        updated=_as_date(meta["updated"], "updated", path),
        blocked_by=list(meta.get("blocked_by") or []),
        github_issue=meta.get("github_issue"),
        owner=_optional_str(meta, "owner", path),
        branch=_optional_str(meta, "branch", path),
        pr=_optional_str(meta, "pr", path),
        closed=_as_date(closed_raw, "closed", path) if closed_raw is not None else None,
        sections=sections,
    )
    _check_lifecycle(ticket)
    return ticket


# Each status names the conditions it demands. A condition is a predicate on
# the ticket and the sentence to report when it fails.
_LIFECYCLE_RULES: dict[str, list[tuple[Callable[[Ticket], bool], str]]] = {
    "in-progress": [
        (
            lambda t: bool(t.owner and t.branch),
            "in-progress needs 'owner' and 'branch', or a second agent will take it",
        ),
    ],
    "in-review": [(lambda t: bool(t.pr), "in-review needs 'pr'")],
    "done": [
        (lambda t: bool(t.pr), "done needs 'pr' -- the merged pull request"),
        (lambda t: t.closed is not None, "done needs 'closed' (the merge date)"),
        (
            lambda t: bool(t.sections.get("Outcome")),
            "done needs a written '## Outcome': what shipped and what was measured",
        ),
        (
            lambda t: t.closed is None or t.closed >= t.created,
            "'closed' is before 'created'",
        ),
    ],
    "dropped": [
        (lambda t: t.closed is not None, "dropped needs 'closed'"),
        (lambda t: bool(t.sections.get("Outcome")), "dropped needs a '## Outcome' saying why"),
    ],
}


def _check_lifecycle(t: Ticket) -> None:
    """The fields each status demands. These are what let agents share the file."""
    problems = [
        f"'## {section}' is empty -- a ticket without one is a wish"
        for section in ("Problem", "Definition", "Success metrics")
        if not t.sections.get(section)
    ]
    if t.updated < t.created:
        problems.append("'updated' is before 'created'")
    problems.extend(
        sentence for holds, sentence in _LIFECYCLE_RULES.get(t.status, []) if not holds(t)
    )
    if problems:
        msg = f"{t.path.name}: " + "; ".join(problems)
        raise TicketError(msg)


# --- The whole store ---------------------------------------------------------


def load_tickets(root: Path | None = None) -> list[Ticket]:
    """Every ticket under ``backlog/tickets/``, validated individually and together."""
    base = root or default_root()
    folder = base / "tickets"
    if not folder.is_dir():
        msg = f"no tickets directory at {folder}"
        raise TicketError(msg)
    tickets = [parse_ticket(p) for p in sorted(folder.glob("*.md"))]
    _check_cross_references(tickets)
    return tickets


def _check_cross_references(tickets: list[Ticket]) -> None:
    by_id: dict[str, Ticket] = {}
    for t in tickets:
        if t.id in by_id:
            msg = f"duplicate ticket id {t.id}: {by_id[t.id].path.name} and {t.path.name}"
            raise TicketError(msg)
        by_id[t.id] = t
    for t in tickets:
        _check_blockers(t, by_id)
    _check_branches(tickets)


def _check_blockers(t: Ticket, by_id: dict[str, Ticket]) -> None:
    for dep in t.blocked_by:
        if dep == t.id:
            msg = f"{t.path.name}: cannot be blocked by itself"
            raise TicketError(msg)
        blocker = by_id.get(dep)
        if blocker is None:
            msg = f"{t.path.name}: blocked_by names {dep}, which does not exist"
            raise TicketError(msg)
        if t.status in ("ready", "in-progress", "in-review") and blocker.is_open:
            msg = (
                f"{t.path.name}: is {t.status} but {dep} ({blocker.status}) still blocks it"
                " -- either the dependency is wrong or the status is"
            )
            raise TicketError(msg)


def _check_branches(tickets: list[Ticket]) -> None:
    branches: dict[str, str] = {}
    for t in tickets:
        if t.status != "in-progress" or not t.branch:
            continue
        if t.branch in branches:
            msg = f"branch {t.branch!r} is claimed by both {branches[t.branch]} and {t.id}"
            raise TicketError(msg)
        branches[t.branch] = t.id


def next_id(tickets: list[Ticket]) -> str:
    """The next free ticket id."""
    highest = max((int(t.id[2:]) for t in tickets), default=-1)
    return f"T-{highest + 1:03d}"


# --- The index --------------------------------------------------------------

# Open tickets list what can be picked up first, then what is held, then
# what is waiting on something else.
_STATUS_ORDER = {
    s: i for i, s in enumerate(("ready", "in-progress", "in-review", "backlog", "done", "dropped"))
}


def _sort_key(t: Ticket) -> tuple[int, int, str]:
    return (_STATUS_ORDER[t.status], PRIORITIES.index(t.priority), t.id)


def _row(t: Ticket) -> str:
    blockers = ", ".join(t.blocked_by) or "—"
    holder = t.owner or "—"
    if t.branch:
        holder = f"{holder} · `{t.branch}`"
    pr = t.pr or "—"
    if t.pr and t.pr.startswith("http"):
        pr = f"[{t.pr.rsplit('/', 1)[-1]}]({t.pr})"
    # Resolved from blob/<ref>/backlog/BACKLOG.md, so three levels up is the repository.
    issue = f"[#{t.github_issue}](../../../issues/{t.github_issue})" if t.github_issue else "—"
    return (
        f"| [{t.id}]({t.link}) | {t.title} | {t.phase} | {t.priority} | {t.status} "
        f"| {blockers} | {holder} | {pr} | {issue} |"
    )


def render_index(tickets: list[Ticket]) -> str:
    """The Markdown index of every ticket, open first."""
    head = "| Id | Title | Phase | Pri | Status | Blocked by | Holder | PR | Issue |"
    rule = "|---|---|---|---|---|---|---|---|---|"
    open_rows = [_row(t) for t in sorted(tickets, key=_sort_key) if t.is_open]
    closed_rows = [
        _row(t)
        for t in sorted(
            (t for t in tickets if not t.is_open),
            key=lambda t: (t.closed or t.updated, t.id),
            reverse=True,
        )
    ]
    parts = [INDEX_HEADER, "## Open", ""]
    parts.extend([head, rule, *open_rows] if open_rows else ["_Nothing open._"])
    parts.extend(["", "## Closed", ""])
    parts.extend([head, rule, *closed_rows] if closed_rows else ["_Nothing closed yet._"])
    return "\n".join(parts) + "\n"


def index_path(root: Path | None = None) -> Path:
    """Where the generated index lives."""
    return (root or default_root()) / "BACKLOG.md"


def write_index(root: Path | None = None) -> Path:
    """Regenerate ``BACKLOG.md`` and return its path."""
    tickets = load_tickets(root)
    target = index_path(root)
    target.write_text(render_index(tickets), encoding="utf-8")
    return target


def check(root: Path | None = None) -> list[Ticket]:
    """Validate every ticket and confirm the index is current.

    Raises ``TicketError`` naming the first problem found. Returns the
    tickets when everything is consistent.
    """
    tickets = load_tickets(root)
    target = index_path(root)
    expected = render_index(tickets)
    if not target.exists() or target.read_text(encoding="utf-8") != expected:
        msg = f"{target.name} is stale -- run `go2 backlog index` and commit the result"
        raise TicketError(msg)
    return tickets


def ready(tickets: list[Ticket]) -> list[Ticket]:
    """Tickets an agent may pick up now, highest priority first."""
    return sorted((t for t in tickets if t.status == "ready"), key=_sort_key)


def new_ticket_text(
    ticket_id: str,
    title: str,
    *,
    phase: str,
    priority: str = "P2",
    today: date | None = None,
) -> str:
    """The skeleton of a new ticket, ready to be filled in."""
    stamp = (today or datetime.now(tz=UTC).date()).isoformat()
    # Through the YAML emitter, so a colon or a bracket in the title cannot
    # produce a file the parser then refuses.
    title_line = yaml.safe_dump({"title": title}, allow_unicode=True, width=10_000).strip()
    return f"""---
id: {ticket_id}
{title_line}
status: backlog
phase: {phase}
priority: {priority}
blocked_by: []
github_issue:
owner:
branch:
pr:
created: {stamp}
updated: {stamp}
closed:
---

## Problem

<!-- What is wrong or missing today, with evidence. Measured, not suspected. -->

## Definition

<!-- What this ticket delivers, and what it explicitly does not. -->

## Success metrics

<!-- How we will know it worked. Numbers where possible, and how to measure them. -->

## Test cases

<!-- The tests that define done, by name. A ticket without them is a wish. -->

## Design notes

<!-- Constraints, invariants touched, options considered. Optional. -->

## Work log

<!-- Dated entries. One line per meaningful step, newest last. -->

## Outcome

<!-- Filled in when the PR merges: what shipped, what was measured, what was left out. -->
"""


def slugify(title: str) -> str:
    """A filename-safe fragment of a title."""
    slug = re.sub(r"[^a-z0-9]+", "-", title.lower()).strip("-")
    return slug[:60].rstrip("-") or "ticket"
